name: Compile Proto Artifacts using Buf

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    compile-proto:
        runs-on: ubuntu-latest

        steps:
            - 
                name: Checkout
                uses: actions/checkout@v4
            
            -
                name: Setup Java
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: '21'

            - 
                name: Install Protoc
                uses: arduino/setup-protoc@v3             

            - 
                name: Replace Secrets in pom.xml and settings.xml
                run: |
                    sed -i "s|\${secrets.NEXUS_URL}|${{ secrets.NEXUS_URL }}|g" pom.xml 
                    sed -i "s|\${secrets.NEXUS_USERNAME}|${{ secrets.NEXUS_USERNAME }}|g" .m2/settings.xml 
                    sed -i "s|\${secrets.NEXUS_PASSWORD}|${{ secrets.NEXUS_PASSWORD }}|g" .m2/settings.xml 

            -
                name: Copy Proto files to separate folder
                run: |
                    mkdir -p generated/.m2
                    mkdir -p generated/src/main/java/
                    mkdir -p generated/src/main/proto
                    
                    cp -r protos/* generated/src/main/proto
                    cp .m2/settings.xml generated/.m2/
                    cp pom.xml generated/

            -
                name: Copy common files to separate folder
                run: |

                    for SRC_FILE in common-files/*.java; do
                        PACKAGE_PATH=$(grep '^package ' "$SRC_FILE" | sed 's/package //' | sed 's/;//' | tr '.' '/')
                        TARGET_DIR="generated/src/main/java/$PACKAGE_PATH"
                        mkdir -p "$TARGET_DIR"
                        cp "$SRC_FILE" "$TARGET_DIR/"
                    done

            - 
                name: Download protoc-gen-grpc-java
                run: |
                    mkdir -p protoc-bin
                    curl -L -o protoc-bin/protoc-gen-grpc-java \
                        https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.71.0/protoc-gen-grpc-java-1.71.0-linux-x86_64.exe
                    chmod +x protoc-bin/protoc-gen-grpc-java

            - 
                name: Compile, Build and Deploy
                working-directory: ./generated
                run: |
                    protoc -I=src/main/proto \
                        --java_out=src/main/java \
                        --grpc-java_out=src/main/java \
                        --plugin=protoc-gen-grpc-java=../protoc-bin/protoc-gen-grpc-java \
                        $(find src/main/proto -name "*.proto")
                    mvn -B -s .m2/settings.xml clean deploy
               
            -
                name: Commit and push stubs to proto-stubs-view repository
                run: |
                    BRANCH_NAME=stubs-update-$(echo $GITHUB_SHA | cut -c1-7)

                    git config --global user.name "github-actions"
                    git config --global user.email "actions@github.com"
                    git clone https://x-access-token:${{ secrets.ACTIONS_USER_TOKEN }}@github.com/ecmsp-project/proto-stubs-view.git

                    cd proto-stubs-view 
                    git checkout -b $BRANCH_NAME
                    git rm -r *

                    cp -r ../generated/* .
                    rm -rf .m2

                    git add .
                    git commit -m "compile new version of .proto files"

                    git checkout main
                    git reset --hard $BRANCH_NAME
                    git push origin main --force


